version: 2.1

parameters:
  short_git_revision:
    type: string
    default: ${CIRCLE_SHA1:0:7}

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      #docker_layer_caching: true
    resource_class: medium
    parameters:
      image_tag: $short_git_revision
    steps:
      - checkout
      - run: |
          sudo apt-get install -y docker-buildx-plugin
      - run: |
          echo "$GITHUB_ACCESS_KEY" | docker login -u seungjin --password-stdin ghcr.io
      - run: |
          docker build -f Containerfile \
          -t ghcr.io/seungjin/atomic-desktop-image:${image_tag} .
      - run: |
          docker push ghcr.io/seungjin/atomic-desktop-image:${image_tag}
      - run: |
          docker buildx imagetools create \
          -t ghcr.io/seungjin/atomic-desktop-image:latest \
          ghcr.io/seungjin/atomic-desktop-image:${image_tag}

workflows:
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "30 18 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
